DoiServer/config/routes.rb
DoiServer::Application.routes.draw do
  resources :reviews

  resources :urls

  resources :dois

  get "home/index"
  devise_for :users

  root :to => "home#index"

  get "udois" => 'dois#udois'
  get "search" => 'dois#search'

  

end

DoiServer/app/models/doi.rb
class Doi < ActiveRecord::Base

	belongs_to :user
	has_many :urls, :dependent => :destroy
	has_many :reviews, :dependent => :destroy
	attr_accessor :url

	validates :name, :presence => true
	validates :description, :presence => true
	validates_uniqueness_of :name

end

DoiServer/app/controllers/dois_controller.rb
class DoisController < ApplicationController
  before_action :check_user!, except: [:search]
  before_action :set_doi, only: [:show, :edit, :update, :destroy]

  # GET /dois
  # GET /dois.json
  def index
    @dois = Doi.all
  end

  # Will perform our search.
  def search
	  @dois = Doi.where("name = ?", params[:query])
	  if @dois.count == 0
		  redirect_to root_path, :alert => 'No DOIs found'
	  end
  end

  # This will retrieve the dois for the current user.
  def udois
    @dois = Doi.find(:all, :conditions => ["user_id = ?", current_user.id])
  end

  # GET /dois/1
  # GET /dois/1.json
  def show
  end

  # GET /dois/new
  def new
    @doi = Doi.new(:user_id => params[:user_id])
  end

  # GET /dois/1/edit
  def edit
    if current_user.id != @doi.user_id
    	redirect_to root_path, :alert => 'Don\'t be bad. You can\'t do that!'
    else
    	@doi.url = Url.where("doi_id = ?", params[:id]).last.url
    end
  end

  # POST /dois
  # POST /dois.json
  def create
    @doi = Doi.new(doi_params)

    if @doi.save
	    @url = Url.new
	    @url.doi_id=@doi.id
	    if params[:doi][:url] =~ /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/
		    @url.url = params[:doi][:url]
		    format.html { render action: 'new' }
	    	    @url.save
	    else
		    format.html { render action: 'new' }
	    end
    end

    respond_to do |format|
      if @doi.save
        format.html { redirect_to @doi, notice: 'Doi was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doi }
      else
        format.html { render action: 'new' }
        format.json { render json: @doi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dois/1
  # PATCH/PUT /dois/1.json
  def update
    if @doi.urls.last.url != params[:doi][:url]
    	@url = Url.new
    	@url.doi_id = @doi.id

    	if params[:doi][:url] =~ /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/
    		@url.url = params[:doi][:url]
    	else
		redirect_to @doi, alert: 'A full URL is required. Ex: http://www.google.com'
		return
    	end

    	if !@url.save
		redirect_to @doi, alert: 'Failed to update the URL, please try again.'
    	end
    end

    	respond_to do |format|
      	if @doi.update(doi_params)
        	format.html { redirect_to @doi, notice: 'Doi was successfully updated.' }
        	format.json { head :no_content }
      	else
        	format.html { render action: 'edit' }
        	format.json { render json: @doi.errors, status: :unprocessable_entity }
      	end
     end
  end

  # DELETE /dois/1
  # DELETE /dois/1.json
  def destroy

    if current_user.id != @doi.user_id
	    redirect_to root_path, alert: 'Don\'t be bad! You can\'t do that.'
	    return
    end

    @doi.destroy
    respond_to do |format|
      format.html { redirect_to dois_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doi
      @doi = Doi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doi_params
      params.require(:doi).permit(:name, :description, :user_id, :url)
    end
end

DoiServer/app/helpers/dois_helper.rb
module DoisHelper
end

DoiServer/app/views/dois/_eform.html.erb
<%= form_for(@doi, :html => {:class => 'form-horizontal'}) do |f| %>
<% if @doi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doi.errors.count, "error") %> prohibited this doi from being saved:</h2>

      <ul>
      <% @doi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="containter">
  <div class="col-md-12">

  <div class="input-group input-group-md">
	  <span class="input-group-addon"><%= f.label :name %></span>
	  <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-md">
	  <span class="input-group-addon"><%= f.label "Desc" %></span>
	  <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-md">
	  <span class="input-group-addon"><%= f.label "Url" %></span>
	  <%= f.text_field :url, :class => 'form-control' %>
  </div>

</div>

  <%= f.hidden_field :user_id %>
  <%= f.hidden_field :id %>

  </div>

  </div>
  <div class="panel-footer">
  <div class="actions">
	  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

DoiServer/app/views/dois/_form.html.erb
<%= form_for(@doi, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @doi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doi.errors.count, "error") %> prohibited this doi from being saved:</h2>

      <ul>
      <% @doi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="containter">
  <div class="col-md-12">

  <div class="input-group input-group-md">
	  <span class="input-group-addon"><%= f.label :name %></span>
	  <%= f.text_field :name, :class => 'form-control' %>
  </div>
  <br>
  <div class="input-group input-group-md">
	  <span class="input-group-addon"><%= f.label "Desc" %></span>
	  <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <br>

  <div class="input-group input-group-md">
	  <span class="input-group-addon"><%= f.label "URL" %></span>
	  <%= f.text_field :url, :class => 'form-control' %>
  </div>
  <br>

  <%= f.hidden_field :user_id %>
  </div>
  </div>

  </div>
  <div class="panel-footer">
  <div class="actions">
	  <%= f.submit :class => 'btn btn-primary' %>
<% end %>

DoiServer/app/views/dois/edit.html.erb
<div class="panel panel-info">
	<div class="panel-heading"><h2>Edit DOI</h2></div>
	<div class="panel-body">
		<%= render 'eform' %>
		<%= link_to 'Back', dois_path, :class => 'btn btn-default' %>
	</div>
</div>

DoiServer/app/views/dois/index.html.erb
<div class="panel panel-info">
	<div class="panel-heading"><h2>All DOIs</h2></div>
	<div class="panel-body">
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>DOI Owner</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @dois.reverse!.each do |doi| %>
      <tr>
        <td><%= doi.name %></td>
	<td><%= link_to(doi.urls.last.url,doi.urls.last.url, url_options = {:confirm => 'You will be leaving DOI Server. Continue?'})  %></td>
        <td><%= doi.user.email %></td>
        <td><%= link_to 'View', doi, :class => 'btn btn-default btn-block' %></td>
	<td><%= link_to 'Review It', new_review_path(:doi_id => doi.id, :user_id => current_user.id), :class => 'btn btn-default btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div

DoiServer/app/views/dois/new.html.erb
<div class="panel panel-info">
	<div class="panel-heading"><h2>Add DOI</h2></div>
	<div class="panel-body">
		<%= render 'form' %>
		<%= link_to 'Back', dois_path, :class => 'btn btn-default' %>
	</div>
</div>

DoiServer/app/views/dois/search.html.erb
<div class="panel panel-info">
	<div class="panel-heading"><h2>Search Results</h2></div>
	<div class="panel-body">
		<table class="table table-condensed table-striped">
  			<thead>
    				<tr>
      					<th>DOI</th>
					<th>Current URL</th>
      					<th>Description</th>
					<th></th>
    				</tr>
  			</thead>

  			<tbody>
    				<% @dois.each do |doi| %>
      					<tr>
        					<td><%= doi.name %></td>
						<td><%= link_to(doi.urls.last.url,doi.urls.last.url, url_options = {:confirm => 'You are leaving DOI server. Continue?'}) %></td>
        					<td><%= doi.description %></td>
						<% if current_user %>
							<td><%= link_to 'View', doi, :class => 'btn btn-default btn-block' %></td>
						<% end %>
      					</tr>
    				<% end %>
  			</tbody>
		</table>
		<div class="panel-footer">
		</div>
	</div>
</div>

DoiServer/app/views/dois/show.html.erb
<div class="panel panel-info">
	<div class="panel-heading"><h2>DOI <small>[ <%= @doi.name %> ]</small></h2></div>
	<div class="panel-body">
		<table class="table table-condensed table-striped">
			<thead>
				<tr>
					<th>DOI</th>
					<th>Current URL</th>
					<th>Description</th>
					<th>Owner</th>
					<th>Created</th>
				</tr>
			</thead>

			<tbody>
				<tr>
					<td><%= @doi.name %></td>
					<td><%= @doi.urls.last.url %></td>
					<td><%= @doi.description %></td>
					<td><%= @doi.user.email %></td>
					<td><%= @doi.user.created_at %></td>
				</tr>
			</tbody>
		</table>
	</div>
	<div class="panel-footer">
		<% if current_user.id == @doi.user_id %>
			<%= link_to 'Edit DOI', edit_doi_path(@doi), :class => 'btn btn-default' %>
		<% end %>
	</div>
</div>

<div class="panel panel-info">
	<div class="panel-heading"><h2>URL History <small>[ <%= @doi.name %> ]</small></h2></div>
	<div class="panel-body">
		<table class="table table-condensed table-striped">
			<thead>
				<tr>
					<th>URL</th>
					<th>Updated</th>
				</tr>
			</thead>

			<tbody>
				<% @doi.urls.reverse!.each do |url| %>
					<tr>
						<td><%= url.url %></td>
						<td><%= url.created_at %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class="panel-footer">
	</div>
</div>
<div class="panel panel-info">
	<div class="panel-heading"><h2>Reviews <small>[ <%= @doi.name %> ]</small></h2></div>
	<div class="panel-body">
		<table class="table table-condensed table-striped">
			<thead>
				<tr>
					<th>Comment</th>
					<th>User</th>
					<th>Date</th>
				</tr>
			</thead>
			<tbody>
				<% @doi.reviews.reverse!.each do |review| %>
					<tr>
						<td><%= review.comment %></td>
						<td><%= review.user.email %></td>
						<td><%= review.created_at %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	<div class="panel-footer">
		<%= link_to 'Add Review', new_review_path(:doi_id => @doi.id, :user_id => current_user.id), :class => 'btn btn-default' %>
	</div>
</div>

DoiServer/app/views/dois/udois.html.erb
<div class="panel panel-info">
	<div class="panel-heading"><h2>User DOIs <small>[ <%= current_user.email %> ]</small></h2></div>
	<div class="panel-body">
		<table class="table table-condensed table-striped">
  			<thead>
    				<tr>
      					<th>DOI</th>
      					<th>Current URL</th>
      					<th>Description</th>
      					<th></th>
      					<th></th>
      					<th></th>
    				</tr>
  			</thead>

  			<tbody>
    				<% @dois.reverse!.each do |doi| %>
      					<tr>
						<td><%= doi.name %></td>
						<td><%= link_to(doi.urls.last.url,doi.urls.last.url, url_options = {:confirm => 'You will be leaving DOI Server. Continue?'})  %></td>
        					<td><%= doi.description %></td>
						<td><%= link_to 'Update', edit_doi_path(doi), :class => 'btn btn-default btn-block' %></td>
        					<td><%= link_to 'View', doi, :class => 'btn btn-default btn-block' %></td>
        					<td><%= link_to 'Destroy', doi, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-block' %></td>
      					</tr>
    				<% end %>
  			</tbody>
		</table>
	</div>
		<div class="panel-footer">
			<%= link_to 'New Doi', new_doi_path(:user_id => current_user.id), :class => 'btn btn-default' %>
		</div>
	</div>
</div>