DoiServer/config/routes.rb
DoiServer::Application.routes.draw do
  resources :reviews

  resources :urls

  resources :dois

  get "home/index"
  devise_for :users

  root :to => "home#index"

  get "udois" => 'dois#udois'
  get "search" => 'dois#search'

  

end

DoiServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Doi</title>
    <%= stylesheet_link_tag "application",media: "all","data-turbolinks-track" => true %>
    <%= javascript_include_tag "application","data-turbo-links-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Doi Server</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
		  <li><%= link_to "All DOIs", dois_path %></li>
		  <li><%= form_tag(search_path, :method => "get", :class => 'navbar-form navbar-left', :role => 'form') do %>
			  <div class="form-group">
				  <%= text_field :query, params[:query], :class => 'form-control', :placeholder => 'Search' %>
			  </div>
			  <button class="btn btn-default" type="submit">Search</button>
			  <% end %>
			  </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
	    <li><% if user_signed_in? %><%= link_to current_user.email, udois_path %></li>
                <li><%= link_to "Log Out", destroy_user_session_path, :method => 'delete' %></li>
		  <% else %>
		    <li><%= link_to "Sign up", new_user_registration_path %></li>
 		    <li><%= link_to "Sign in", new_user_session_path %></li>
                <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container" style="margin-top:65px;">

      <div class="container">
		<% if notice %>
		  <div class="alert alert-success"><%= notice %></div>
		<% end %>
		<% if alert %>
	          <div class="alert alert-danger"><%= alert %></div>
		<% end %>

	<%= yield %>

      </div>

    </div><!-- /.container -->
  </body>
</html>

DoiServer/app/views/layouts/old.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoiServer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="user_nav">
<% if user_signed_in? %>
Signed in as <%= current_user.email %>. Not you?
<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
<%= link_to "Sign up", new_user_registration_path %> or
<%= link_to "Sign in", new_user_session_path %>
<% end %>
</div>

<%= yield %>

</body>
</html>