DoiServer/config/routes.rb
DoiServer::Application.routes.draw do
  resources :reviews

  resources :urls

  resources :dois

  get "home/index"
  devise_for :users

  root :to => "home#index"

  get "udois" => 'dois#udois'
  get "search" => 'dois#search'

  

end

DoiServer/app/models/url.rb
class Url < ActiveRecord::Base

  belongs_to :doi

  validates :url, :presence => true, format: {:with => /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$\z/ }
  validates :doi_id, :presence => true


end

DoiServer/app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :check_user!
  before_action :set_url, only: [:show, :edit, :update, :destroy]

  # GET /urls
  # GET /urls.json
  def index
    @urls = Url.all
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new(:doi_id => params[:doi_id])
  end

  # GET /urls/1/edit
  def edit
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, notice: 'Url was successfully created.' }
        format.json { render action: 'show', status: :created, location: @url }
      else
        format.html { render action: 'new' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:url, :doi_id, :date)
    end
end

DoiServer/app/helpers/urls_helper.rb
module UrlsHelper
end

DoiServer/app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>

  <%= f.hidden_field :doi_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

DoiServer/app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

DoiServer/app/views/urls/index.html.erb
<h1>Listing urls</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Doi</th>
      <th>Date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.url %></td>
        <td><%= url.doi_id %></td>
        <td><%= url.created_at %></td>
        <td><%= link_to 'Show', url %></td>
        <td><%= link_to 'Edit', edit_url_path(url) %></td>
        <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Url', new_url_path %>

DoiServer/app/views/urls/new.html.erb
<h1>Update URL</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

DoiServer/app/views/urls/show.html.erb
<p>
  <strong>Url:</strong>
  <%= @url.url %>
</p>

<p>
  <strong>Doi:</strong>
  <%= @url.doi_id %>
</p>

<%= link_to 'Edit', edit_url_path(@url) %> |
<%= link_to 'Back', urls_path %>